---
ID: "39876fe7-16c4-4cef-aaab-faa281b206f1"
Parent: "7b59a1d4-3a4d-4786-8505-ce9a24abcca7"
Template: "7b59a1d4-3a4d-4786-8505-ce9a24abcca7"
Path: /sitecore/templates/Project/DemoHeadlessTenant/Headless Site/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230524T093839Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "166dfb60-72f8-4f5b-85cd-218e86d6dfbb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230524T093839Z
